version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
    networks:
      - back-tier

  backend:
    build: ./back
    ports:
      - 8080:8080  
    depends_on:  
      - db  
    environment:
      URL_STOCK: https://stooq.com/q/l/?s=%s&f=sd2t2ohlcv&h&e=csv
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - back-tier

  frontend:
    build: ./web
    ports:
      - 5000:80
    depends_on:  
      - backend
    networks:
      - back-tier
      - front-tier

networks:
  back-tier:
  front-tier:
