version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres" 
      # ports: 5432  

  backend:
    build: ./back
    ports:
      - 8080:8080   

  # frontend:
  #     build: ./web
  #     ports:
  #       - 5000:80
    


